AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template for creating an S3 bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled